version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
    - ./local_db/init.sql:/docker-entrypoint-initdb.d/init.sql

  simple-back:
    image: simple-back
    restart: always
      ports:
      - 8000:8000
    environment:
      ENV: local-docker
